name: Deploy Node App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t sereni_island_app
         .

      - name: Run container test
        run: docker run -d -p 3000:3000 sereni_island_app
